### ISSUE TITLE
Team explorer freezes

### ISSUE THREAD

**Issue by niclassparr** [scrubs767/GitStash#12]
When I have GitStash open in teamexplorer Visual studio freezes for about 15-30 seconds when I click on anything in GitStash. 
Visual studio freezes for 3-5 seconds for anything I do (every click and every key pressed) after installing Gitstash.
I use visual studio professional 2015 update 3

**Comment by scrubs767** [comment]
Can you click on Help->About Microsoft Visual Studio, and then on the right side of the dialog that pops up, click copy info and paste it into a message?
