### ISSUE TITLE
Files must be staged first before stashing works

### ISSUE THREAD

**Issue by stefan505** [scrubs767/GitStash#13]
I'm trying out the latest version of the plugin now and I came across the following:

Step 1 - Got some Changes I want to stash:

![image](https://cloud.githubusercontent.com/assets/10812446/22363321/51ffdb02-e472-11e6-8925-0f7f94b4ea3a.png)

Step 2 - Go to Git Stash, enter a stash name and click [Save]:

![image](https://cloud.githubusercontent.com/assets/10812446/22363361/96a7acee-e472-11e6-9b2c-98b77fe56997.png)

I am confused at this point, because I anticipated the tool to stash the changes visible in Step 1 above, but instead got the above message. 

Step 3 - Went back to Changes and staged my modification (not committing it).

Step 4 - Went back to Git Stash and repeat Step 2, now it works:

![image](https://cloud.githubusercontent.com/assets/10812446/22363454/2a87cdb8-e473-11e6-98db-5e6d581207ba.png)

Why was it required to first stage my change prior to creating the stash? 

Operating System: **Windows 10 Pro**
Visual Studio: **2015 Community - Update 3**
Git:  **2.11.0.windows.1**
GitStash: **1.3**

**Comment by scrubs767** [comment]
No its is not supposed to work that way, is settings.cs a new file? Is it possible for you to share the project or re-create a project that has the same behavior?

**Comment by stefan505** [comment]
Not Settings.cs is not a new file. 

Here's your repro: https://github.com/stefan505/gitstash-repro/blob/master/README.md

**Comment by stefan505** [comment]
@scrubs767, did you look at my repro?

**Comment by scrubs767** [comment]
not yet, I havnt had time
