### ISSUE TITLE
Freeze when I click on it

### ISSUE THREAD

**Issue by ranouf** [scrubs767/GitStash#14]
HI,

I have Visual Studio 2015 Community Update 3.

I just installed the plugin, I click on Git Stash in Team Work Tab and the app froze.

**Comment by scrubs767** [comment]
Visual studio froze or git stash?

**Comment by ranouf** [comment]
Sorry for the delay, Visual studio, i had to desintall the plugin. Now VS works correctly

**Comment by robert-skarzycki** [comment]
Same story - VS freezes when I click on GitStash in Team Explorer.
VS Enterprise 2015
14.0.25431.01 Update 3

**Comment by Webrusterkk** [comment]
+1
