### ISSUE TITLE
System.MissingMethodException error

### ISSUE THREAD

**Issue by OZ1** [scrubs767/GitStash#3]
I get two errors in Visual Studio 14.0.24720.00:
System.MissingMethodException: Метод не найден: "Void GitStash.ViewModels.RecommendedActionsViewModel..ctor(GitWrapper.IGitStashWrapper, TeamExplorer.Common.ITeamExplorerBase)".
   в GitStash.Sections.RecommendedActionsSection.Initialize(Object sender, SectionInitializeEventArgs e)
   в Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)
and
System.MissingMethodException: Метод не найден: "Void GitStash.ViewModels.StashesViewModel..ctor(GitWrapper.IGitStashWrapper, TeamExplorer.Common.ITeamExplorerBase, SecondLanguage.Translator)".
   в GitStash.Sections.StashesSection.Initialize(Object sender, SectionInitializeEventArgs e)
   в Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)
![gitstash](https://cloud.githubusercontent.com/assets/1448985/14077730/d32245fc-f4ff-11e5-8518-3df5a3b43527.png)

**Comment by scrubs767** [comment]
Did you upgrade the extension and get it, or did just install it and you got this when you started it up?

**Comment by scrubs767** [comment]
Closed for no response
