### ISSUE TITLE
Problem using GitStash in Visual Studio 2015 

### ISSUE THREAD

**Issue by NTTAKR** [scrubs767/GitStash#5]
Hi!

I would desparately need your extension to work, because MS did remove include/exclude feature from Team Explorer with the last update. 

But as soon as I install your extension all Tabs in Team Explorer (except setup) are broken and result in an exception being thrown. 

Can you please update your solution? 

Best regards,
  Andreas Kroll

**Comment by scrubs767** [comment]
please send the exception information, otherwise there is nothing I can do.

**Comment by NTTAKR** [comment]
Here is the list of Exceptions I get: 

------------------------------------------------------------------------------------------------------------------
System.TypeLoadException: Die Methode "CreateItem" im Typ "Microsoft.TeamFoundation.Git.Controls.PendingChanges.GitPendingChangeFileListViewHelper" der Assembly "Microsoft.TeamFoundation.Git.Controls, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" hat keine Implementierung.
   bei Microsoft.TeamFoundation.Git.Controls.PendingChanges.GitPendingChangesModel..ctor(IServiceProvider serviceProvider, IGitPendingChangesProvider dataProvider, TaskFactory taskFactory)
   bei Microsoft.TeamFoundation.Git.Controls.PendingChanges.GitPendingChangesPage.CreateModel(PageInitializeEventArgs e)
   bei Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.TeamExplorerPageBase.Initialize(Object sender, PageInitializeEventArgs e)
   bei Microsoft.TeamFoundation.Git.Controls.GitTeamExplorerPageBase.Initialize(Object sender, PageInitializeEventArgs e)
   bei Microsoft.TeamFoundation.Git.Provider.PendingChanges.GitPendingChangesPageVS.Initialize(Object sender, PageInitializeEventArgs e)
   bei Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerPageHost.Initialize(TeamExplorerPageContext context)
------------------------------------------------------------------------------------------------------------------
System.TypeLoadException: Der Typ "Microsoft.TeamFoundation.Controls.ITeamExplorerSectionCommand" in der Assembly "Microsoft.TeamFoundation.Controls, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" konnte nicht geladen werden.
   bei Microsoft.TeamFoundation.Git.Controls.PendingChanges.WorkItemsSection.Initialize(Object sender, SectionInitializeEventArgs e)
   bei Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)
------------------------------------------------------------------------------------------------------------------
System.TypeLoadException: Der Typ "Microsoft.TeamFoundation.Controls.ITeamExplorerSectionCommand" in der Assembly "Microsoft.TeamFoundation.Controls, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" konnte nicht geladen werden.
   bei Microsoft.TeamFoundation.Git.Controls.PendingChanges.StagedChangesSection.Initialize(Object sender, SectionInitializeEventArgs e)
   bei Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)
------------------------------------------------------------------------------------------------------------------
System.TypeLoadException: Der Typ "Microsoft.TeamFoundation.Controls.ITeamExplorerSectionCommand" in der Assembly "Microsoft.TeamFoundation.Controls, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" konnte nicht geladen werden.
   bei Microsoft.TeamFoundation.Git.Controls.PendingChanges.UnstagedChangesSection.Initialize(Object sender, SectionInitializeEventArgs e)
   bei Microsoft.TeamFoundation.Controls.WPF.TeamExplorer.Framework.TeamExplorerSectionHost.Initialize(Object context)

**Comment by NTTAKR** [comment]
Any news on the source of the exception yet?

**Comment by scrubs767** [comment]
I have a build I would like you to try, rename this GitStash.vsix and double click, it should install automatically.
[GitStash.zip](https://github.com/scrubs767/GitStash/files/629051/GitStash.zip)

**Comment by scrubs767** [comment]
This issue isn't coming from my code, but from "Microsoft.TeamFoundation.Git.Controls.PendingChanges.GitPendingChangeFileListViewHelper
