### ISSUE TITLE
GitFlow Doesn't Always Appear in Home Dropdown List

### ISSUE THREAD

**Issue by yannduran** [scrubs767/GitStash#7]
When you click on the Home icon, you can see the GitStach icon. When you click the dropdown next to the selected function in the Home tab GitStash doesn't appear in the list.

To reproduce this:

1. Click on the GitStash icon in the Home tab (GitStash DOES appear at the top of the dropdown list, and is ticked)
2. Select Changes (or any other item in the dropdown list)
3. Try to go back to GitStash using the dropdown again (GitStash is NOT in the list, like Changes, Branches etc is)

I love using GitStash, and I also use the Team Explorer dropdown a lot to switch between Team Explorer functions (eg clicking Changes, making a commit, then clicking Sync, then maybe clicking Work Items). Not having GitStash in the dropdown means that I always have to go back to the Home tab first (using the Home icon), then click on the GitStash icon. I can use the dropdown for everything except GitStash.

Jakob Ehn had the same problem in his GitFlow.VS extension, I reported the issue to him in [Issue #29](https://github.com/jakobehn/GitFlow.VS/issues/29). He researched it and fix the issue in GitFlow.VS. It turned out that the fix was trivial, so I'll create a pull request with the code to fix the issue here GitStash.

**Comment by scrubs767** [comment]
I have a commit to fix this, thank you.

**Comment by yannduran** [comment]
My intention was to save you the trouble by submitting a pull request (which I did).

**Comment by scrubs767** [comment]
Thank you very much
